version: "3.9"

services:
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 1337:80
    volumes: 
      - ./nginx/js:/etc/nginx/js
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
